apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: curator
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            parent: cronjob_curator
        spec:
          containers:
          - command:
            - curator/curator
            - --config=curator/config/curator.yaml
            - curator/config/actions.yml
            image: docker-registry.default.svc:5000/viaa-logging/curator@sha256:216e1251f4aba7ba30023ed1ff04bf70caee3e8dcb71ee6da543afafdbe65887
            imagePullPolicy: IfNotPresent
            name: curator
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
            - mountPath: /curator/config
              name: curator
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 511
              name: curator
            name: curator
  schedule: 01 08 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
status:
  lastScheduleTime: 2019-06-07T08:01:00Z

