apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: filebeat-okd
objects:
- apiVersion: extensions/v1beta1
  kind: DaemonSet
  metadata:
    creationTimestamp: null
    generation: 4
    labels:
      k8s-app: filebeat
      kubernetes.io/cluster-service: "true"
    name: filebeat
  spec:
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    template:
      metadata:
        creationTimestamp: null
        labels:
          k8s-app: filebeat
          kubernetes.io/cluster-service: "true"
      spec:
        containers:
        - args:
          - -c
          - /etc/filebeat.yml
          - -e
          env:
          - name: ELASTICSEARCH_HOST
            value: es-ingest-prd.viaa-elk.svc
          - name: ELASTICSEARCH_PORT
            value: "9200"
          - name: ELASTICSEARCH_USERNAME
            value: elastic
          - name: ELASTICSEARCH_PASSWORD
            value: elastic
          - name: ELASTIC_CLOUD_ID
          - name: ELASTIC_CLOUD_AUTH
          image: docker.elastic.co/beats/filebeat:7.1.0
          imagePullPolicy: IfNotPresent
          name: filebeat
          resources:
            limits:
              memory: 400Mi
            requests:
              cpu: 300m
              memory: 100Mi
          securityContext:
            privileged: true
            runAsUser: 0
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/filebeat.yml
            name: config
            readOnly: true
            subPath: filebeat.yml

          - mountPath: /usr/share/filebeat/data
            name: data
          - mountPath: /var/lib/docker/containers
            name: varlibdockercontainers
            readOnly: true

          - name: inputs
            mountPath: /usr/share/filebeat/inputs.d
            readOnly: true

        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: filebeat
        serviceAccountName: filebeat
        terminationGracePeriodSeconds: 30
        volumes:
        - configMap:
            defaultMode: 384
            name: filebeat-config
          name: config
        - hostPath:
            path: /var/lib/docker/containers
            type: ""
          name: varlibdockercontainers
        - name: inputs
          configMap:
            defaultMode: 0600
            name: filebeat-inputs

        - emptyDir: {}
          name: data
    templateGeneration: 4
    updateStrategy:
      type: OnDelete
  status:

- apiVersion: v1
  data:
    filebeat.yml: |
      filebeat.config:
        inputs:
          # Mounted `filebeat-inputs` configmap:
          path: ${path.config}/inputs.d/*.yml
          # Reload inputs configs as they change:
          reload.enabled: false
        modules:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload.enabled: false

      processors:
        - add_cloud_metadata:

      cloud.id: ${ELASTIC_CLOUD_ID}
      cloud.auth: ${ELASTIC_CLOUD_AUTH}

      output.elasticsearch:
        hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: ${ELASTICSEARCH_USERNAME}
        password: ${ELASTICSEARCH_PASSWORD}
        ilm.enabled: false
  kind: ConfigMap
  metadata:
    creationTimestamp: null
    labels:
      k8s-app: filebeat
      kubernetes.io/cluster-service: "true"
    name: filebeat-config

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: filebeat-inputs
    namespace: kube-system
    labels:
      k8s-app: filebeat
  data:
    kubernetes.yml: |-
      - type: docker
        containers.ids:
        - "*"
        processors:
          - add_kubernetes_metadata:
              in_cluster: true


- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRoleBinding
  metadata:
    name: filebeat
  subjects:
  - kind: ServiceAccount
    name: filebeat
    namespace: viaa-elk
  roleRef:
    kind: ClusterRole
    name: filebeat
    apiGroup: rbac.authorization.k8s.io

- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: ClusterRole
  metadata:
    name: filebeat
    labels:
      k8s-app: filebeat
  rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
    - namespaces
    - pods
    verbs:
    - get
    - watch
    - list

- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: filebeat
    namespace: viaa-elk
    labels:
      k8s-app: filebeat
