apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: ss-es7
objects:
- apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    annotations:
    creationTimestamp: null
    generation: 36
    labels:
      ENV: prd
      app: elastic-prd
      component: elasticsearch-prd
      role: master
    name: es-cluster-prd
  spec:
    podManagementPolicy: OrderedReady
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        component: elasticsearch-prd
        role: master
    serviceName: elasticsearch-prd
    template:
      metadata:
        creationTimestamp: null
        labels:
          component: elasticsearch-prd
          role: master
      spec:
        containers:
        - env:
          - name: ENV
            value: prd
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: ES_PLUGINS_INSTALL
          - name: CLUSTER_NAME
            value: es-7.5.0-prd
          - name: NODE_MASTER
            value: "true"
          - name: NODE_INGEST
            value: "true"
          - name: ES_JAVA_OPTS
            value: -Xms1800m -Xmx1800m
          - name: PROCESSORS
            value: "1"
          - name: DISCOVERY_SERVICE
            value: es-discover-prd
          image: docker-registry.default.svc:5000/viaa-elk/elastic-prd:latest
          imagePullPolicy: Always
          name: es-cluster-prd
          ports:
          - containerPort: 9200
            name: http
            protocol: TCP
          - containerPort: 9300
            name: transport
            protocol: TCP
          resources:
            limits:
              memory: 2100Mi
            requests:
              memory: 1400Mi
          livenessProbe:
            failureThreshold: 30
            initialDelaySeconds: 180
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: transport
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /_cluster/health
              port: http
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 12

          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: es-storage
        dnsPolicy: ClusterFirst
        initContainers:
        - command:
          - /bin/sh
          - -c
          - sysctl -w vm.max_map_count=262144
          image: busybox:1.27.2
          imagePullPolicy: IfNotPresent
          name: init-sysctl
          resources: {}
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RESOURCE
            privileged: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    updateStrategy:
      rollingUpdate:
        partition: 0
      type: RollingUpdate
    volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: es-storage
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 200Gi
        storageClassName: vsphere-standard
      status:
        phase: Pending
  status:
