cluster:
  name: ${CLUSTER_NAME}

node:
  name: ${NODE_NAME}

#network.host: ${NETWORK_HOST}
network.host: _site_

path:
  data: /data/data
  logs: /data/log
  repo: ${REPO_LOCATIONS}

bootstrap:
  memory_lock: ${MEMORY_LOCK}

http:
  cors:
    enabled: true
    allow-origin: ${HTTP_CORS_ALLOW_ORIGIN}

#discovery:
#  seed_hosts:
#    - ${DISCOVERY_SERVICE}
xpack.ml.enabled: false

gateway.recover_after_nodes: 2
gateway.expected_nodes: 3


# RE-ENABLE once at es7 and java 11
# Bootstrap the cluster using an initial set of master-eligible nodes:
#
discovery.seed_hosts: ["es-cluster-${env}-0", "es-cluster-${env}-1", "es-cluster-${env}-2"]
cluster.initial_master_nodes: ["es-cluster-${env}-0", "es-cluster-${env}-1", "es-cluster-${env}-2"]
